// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5Ej88fTHAhU8a2Q-ZL99DwUdjX0_jspE',
    appId: '1:310249726693:web:3d3d108ca0a8ac6c776a0c',
    messagingSenderId: '310249726693',
    projectId: 'ecommerceapp-6cb2e',
    authDomain: 'ecommerceapp-6cb2e.firebaseapp.com',
    storageBucket: 'ecommerceapp-6cb2e.firebasestorage.app',
    measurementId: 'G-CE3BSVV9FB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkvqNXnB4jYyo8xJljgSmYoBcLjjyvMZQ',
    appId: '1:310249726693:android:248000992bfd0613776a0c',
    messagingSenderId: '310249726693',
    projectId: 'ecommerceapp-6cb2e',
    storageBucket: 'ecommerceapp-6cb2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOn3u9MliyqMDUQY8cKjpg931T6jecqks',
    appId: '1:310249726693:ios:ace57960f70e3c0a776a0c',
    messagingSenderId: '310249726693',
    projectId: 'ecommerceapp-6cb2e',
    storageBucket: 'ecommerceapp-6cb2e.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOn3u9MliyqMDUQY8cKjpg931T6jecqks',
    appId: '1:310249726693:ios:ace57960f70e3c0a776a0c',
    messagingSenderId: '310249726693',
    projectId: 'ecommerceapp-6cb2e',
    storageBucket: 'ecommerceapp-6cb2e.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5Ej88fTHAhU8a2Q-ZL99DwUdjX0_jspE',
    appId: '1:310249726693:web:5c8ee0cad0afe8ac776a0c',
    messagingSenderId: '310249726693',
    projectId: 'ecommerceapp-6cb2e',
    authDomain: 'ecommerceapp-6cb2e.firebaseapp.com',
    storageBucket: 'ecommerceapp-6cb2e.firebasestorage.app',
    measurementId: 'G-7XMWM30GX2',
  );
}
